import React, { useState, useMemo, useEffect } from 'react';
import AppNav from '../components/AppNav';

/* =========================================================================
 * COACH ENGINE — Module 5 Proof-of-Concept
 * Demonstrates: cross-module data ingestion, deterministic rule gate,
 *               linear regression on weight, volume regression detection,
 *               macro recommendation with human-readable rationale.
 *
 * Architecture note: the rule gate (decideRecommendation) is the BRAINSTEM —
 * deterministic, testable, predictable. The narrative paragraph would be
 * generated by Claude in production (the CORTEX) — given the same numeric
 * context, it explains WHY in human language. Rules decide; AI explains.
 * ========================================================================= */

// -------------------- DOMAIN MODEL --------------------
const MUSCLES = {
  chest: 'Chest',
  front_delts: 'Front Delts',
  triceps: 'Triceps',
  lats: 'Lats',
  biceps: 'Biceps',
  quads: 'Quads',
  hamstrings: 'Hamstrings',
  glutes: 'Glutes',
};

// In production: this object is hydrated from three Supabase queries —
// biometric_entries, nutrition_logs, and a rolling-window volume view.
const USER_CONTEXT = {
  userId: 'demo-user',
  name: 'Marcus',
  goal: 'cut',
  programWeek: 5,
  programDuration: 12,
  startWeight: 82.0,
  currentMacros: { kcal: 2200, protein: 180, carbs: 200, fat: 70 },
  weightLog: [
    82.0, 81.9, 81.8, 81.9, 81.7, 81.6, 81.5,
    81.4, 81.2, 81.1, 81.0, 80.8, 80.6, 80.4,
  ],
  calorieLog: [
    2180, 2230, 2210, 2150, 2240, 2200, 2180,
    2210, 2190, 2220, 2200, 2180, 2210, 2200,
  ],
  proteinLog: [
    178, 185, 182, 175, 188, 180, 178,
    182, 179, 184, 181, 177, 183, 180,
  ],
  // % volume change last 14 days vs prior 14 days
  volumeChange: {
    chest: -8.2,
    front_delts: -3.1,
    triceps: 1.5,
    quads: -5.4,
    glutes: 2.1,
    lats: -2.9,
    biceps: 0.5,
    hamstrings: -1.8,
  },
  daysUntilNext: 2,
  lastAnalyzed: '2 minutes ago',
};

// -------------------- LOGIC --------------------

// Linear regression — returns {slope, intercept} where slope is kg/day.
function linearRegression(values) {
  const n = values.length;
  if (n < 2) return { slope: 0, intercept: values[0] || 0 };
  const meanX = (n - 1) / 2;
  const meanY = values.reduce((a, b) => a + b, 0) / n;
  let num = 0, den = 0;
  for (let i = 0; i < n; i++) {
    num += (i - meanX) * (values[i] - meanY);
    den += (i - meanX) ** 2;
  }
  const slope = den === 0 ? 0 : num / den;
  return { slope, intercept: meanY - slope * meanX };
}

const mean = (arr) => arr.reduce((a, b) => a + b, 0) / arr.length;
const fmt0 = (n) => Math.round(n).toLocaleString('en-US');
const fmt1 = (n) => n.toFixed(1);

// THE RULE GATE — deterministic, testable, returns the decision + reasoning trail.
function decideRecommendation(ctx) {
  const { slope } = linearRegression(ctx.weightLog);
  const slopeKgPerWeek = slope * 7;
  const slopePctPerWeek = (slopeKgPerWeek / ctx.startWeight) * 100;
  const regressingMuscles = Object.entries(ctx.volumeChange)
    .filter(([, v]) => v < -5)
    .map(([k]) => k);

  // Trail records every gate the data passed through — used to highlight
  // the active path in the decision tree visualization below.
  const trail = ['root'];
  let decision = { kcalDelta: 0, deload: false, label: 'Hold', kind: 'hold' };

  if (ctx.goal === 'cut') {
    trail.push('goal_cut');
    if (slopePctPerWeek >= -0.3) {
      trail.push('slope_stalled');
      decision = { kcalDelta: -100, deload: false, label: 'Increase deficit', kind: 'cut_deeper' };
    } else if (slopePctPerWeek < -0.7) {
      trail.push('slope_aggressive');
      if (regressingMuscles.length >= 3) {
        trail.push('volume_regressing');
        decision = { kcalDelta: +150, deload: true, label: 'Add calories + deload', kind: 'recover' };
      } else {
        trail.push('volume_holding');
        decision = { kcalDelta: +100, deload: false, label: 'Add calories', kind: 'protect' };
      }
    } else {
      trail.push('slope_on_target');
      decision = { kcalDelta: 0, deload: false, label: 'Hold course', kind: 'hold' };
    }
  }

  return {
    slope,
    slopeKgPerWeek,
    slopePctPerWeek,
    regressingMuscles,
    trail,
    decision,
  };
}

// Macro re-allocation. Adding kcal: 30% protein, 50% carbs, 20% fat.
// Removing kcal: cut 80% from carbs, 20% from fat (preserve protein).
function applyMacroDelta(current, kcalDelta) {
  if (kcalDelta === 0) return { ...current };
  const ratio = kcalDelta > 0 ? { p: 0.30, c: 0.50, f: 0.20 } : { p: 0.0, c: 0.80, f: 0.20 };
  const p = Math.round((kcalDelta * ratio.p) / 4);
  const c = Math.round((kcalDelta * ratio.c) / 4);
  const f = Math.round((kcalDelta * ratio.f) / 9);
  return {
    kcal: current.kcal + kcalDelta,
    protein: current.protein + p,
    carbs: current.carbs + c,
    fat: current.fat + f,
  };
}

// Rationale text — in production, generated by Claude given the full numeric
// context. Mocked here as a representative output.
function generateRationale(ctx, analysis) {
  const { slopePctPerWeek, regressingMuscles, decision } = analysis;
  const weightDelta = ctx.weightLog[0] - ctx.weightLog[ctx.weightLog.length - 1];
  const regList = regressingMuscles.map(m => MUSCLES[m]).join(', ');
  return `Over the last 14 days, weight dropped ${fmt1(weightDelta)} kg — that's ${fmt1(Math.abs(slopePctPerWeek))}% body weight per week, exceeding the 0.7% safe-cut threshold. Training volume is regressing in ${regressingMuscles.length} muscle group${regressingMuscles.length === 1 ? '' : 's'} (${regList || 'none'}), but compound-lift performance hasn't broken down yet. The pattern indicates under-recovery, not overreaching — a small caloric correction should restore performance without reversing fat loss. Recommendation: ${decision.kcalDelta > 0 ? 'add' : 'remove'} ${Math.abs(decision.kcalDelta)} kcal/day, weighted toward carbohydrates for training fuel. ${decision.deload ? 'Pair with a 5-day deload week to allow nervous-system recovery.' : 'Reassess in 7 days — if volume continues regressing, escalate to a deload.'}`;
}

// -------------------- UI --------------------

const fmt = (n, d = 0) => n.toFixed(d);

function StatBlock({ label, value, sub, accent }) {
  return (
    <div className="flex flex-col gap-1 px-5 py-4 border-r border-stone-800/60 last:border-r-0 first:pl-0">
      <span className="text-[10px] uppercase tracking-[0.18em] text-stone-500 font-medium">{label}</span>
      <span className={`text-3xl font-anton tracking-tight tabular-nums ${accent || 'text-stone-100'}`}>{value}</span>
      {sub && <span className="text-[11px] text-stone-500 tabular-nums">{sub}</span>}
    </div>
  );
}

// Sparkline with optional regression overlay
function Sparkline({ values, color = '#ed7a2a', regression = false, height = 50, fill = false }) {
  const min = Math.min(...values);
  const max = Math.max(...values);
  const range = max - min || 1;
  const w = 240;
  const padY = 6;
  const points = values.map((v, i) => {
    const x = (i / (values.length - 1)) * w;
    const y = height - padY - ((v - min) / range) * (height - padY * 2);
    return [x, y];
  });
  const linePath = points.map(([x, y], i) => `${i === 0 ? 'M' : 'L'} ${x.toFixed(1)},${y.toFixed(1)}`).join(' ');
  const fillPath = `${linePath} L ${w},${height} L 0,${height} Z`;

  let regressionPath = '';
  if (regression) {
    const reg = linearRegression(values);
    const yA = reg.intercept;
    const yB = reg.slope * (values.length - 1) + reg.intercept;
    const yAs = height - padY - ((yA - min) / range) * (height - padY * 2);
    const yBs = height - padY - ((yB - min) / range) * (height - padY * 2);
    regressionPath = `M 0,${yAs.toFixed(1)} L ${w},${yBs.toFixed(1)}`;
  }

  return (
    <svg viewBox={`0 0 ${w} ${height}`} className="w-full" preserveAspectRatio="none">
      {fill && <path d={fillPath} fill={color} opacity="0.08" />}
      {regression && (
        <path d={regressionPath} stroke="#ff5a2a" strokeWidth="1" strokeDasharray="4,3" fill="none" opacity="0.7" />
      )}
      <path d={linePath} stroke={color} strokeWidth="1.5" fill="none" vectorEffect="non-scaling-stroke" />
      {points.map(([x, y], i) => (
        <circle
          key={i}
          cx={x} cy={y}
          r={i === points.length - 1 ? 3 : 1.4}
          fill={i === points.length - 1 ? color : color}
          opacity={i === points.length - 1 ? 1 : 0.6}
        />
      ))}
    </svg>
  );
}

// Volume change horizontal bar chart, diverging from center
function VolumeChangeChart({ data }) {
  const entries = Object.entries(data).sort(([, a], [, b]) => a - b);
  const maxAbs = Math.max(...entries.map(([, v]) => Math.abs(v)), 5);

  return (
    <div className="space-y-2">
      {entries.map(([m, v]) => {
        const negative = v < 0;
        const pct = (Math.abs(v) / maxAbs) * 48;
        return (
          <div key={m} className="flex items-center gap-3">
            <div className="w-20 text-[10px] uppercase tracking-wider text-stone-500 font-mono shrink-0">
              {MUSCLES[m]}
            </div>
            <div className="flex-1 relative h-3 bg-stone-900/80">
              <div className="absolute left-1/2 top-0 bottom-0 w-px bg-stone-700/80 z-10" />
              <div
                className="absolute top-0 bottom-0 transition-all duration-500"
                style={{
                  [negative ? 'right' : 'left']: '50%',
                  width: `${pct}%`,
                  background: negative ? 'rgb(180, 70, 60)' : 'rgb(240, 110, 38)',
                }}
              />
            </div>
            <div className={`w-14 text-right font-mono text-[11px] tabular-nums ${negative ? 'text-red-400' : 'text-orange-300'}`}>
              {v > 0 ? '+' : ''}{fmt(v, 1)}%
            </div>
          </div>
        );
      })}
    </div>
  );
}

// Decision flow — vertical step-by-step diagnostic with active branch highlight
function DecisionFlow({ analysis }) {
  const active = (key) => analysis.trail.includes(key);

  // Three stages: GOAL → SLOPE → VOLUME → DECISION
  const slopeBucket =
    analysis.slopePctPerWeek >= -0.3 ? 'slope_stalled' :
    analysis.slopePctPerWeek < -0.7 ? 'slope_aggressive' :
    'slope_on_target';

  const volumeBucket = analysis.regressingMuscles.length >= 3 ? 'volume_regressing' : 'volume_holding';

  const slopeOptions = [
    { id: 'slope_stalled',    label: '≥ -0.3% / wk',           sub: 'cut stalled' },
    { id: 'slope_on_target',  label: '-0.3 to -0.7% / wk',     sub: 'on target' },
    { id: 'slope_aggressive', label: '< -0.7% / wk',           sub: 'too aggressive' },
  ];

  const volumeOptions = [
    { id: 'volume_holding',    label: '< 3 muscles down',  sub: 'holding strength' },
    { id: 'volume_regressing', label: '≥ 3 muscles down',  sub: 'losing strength' },
  ];

  const showVolume = active('slope_aggressive');

  return (
    <div className="space-y-4">
      {/* STAGE 1 — GOAL */}
      <div className="flex items-center gap-3">
        <span className="text-[9px] uppercase tracking-[0.2em] text-stone-600 font-mono w-16 shrink-0">01 · Goal</span>
        <div className="flex-1 px-4 py-3 border border-orange-500/40 bg-orange-500/5">
          <div className="font-anton text-lg uppercase tracking-tight text-orange-300">CUT — Week 5 / 12</div>
        </div>
      </div>

      {/* STAGE 2 — SLOPE */}
      <div className="flex items-start gap-3">
        <span className="text-[9px] uppercase tracking-[0.2em] text-stone-600 font-mono w-16 shrink-0 pt-3">02 · Weight</span>
        <div className="flex-1 grid grid-cols-3 gap-2">
          {slopeOptions.map(opt => {
            const isActive = opt.id === slopeBucket;
            return (
              <div
                key={opt.id}
                className={`px-3 py-2.5 border transition-all ${
                  isActive
                    ? 'border-orange-500/60 bg-orange-500/10'
                    : 'border-stone-800/60 bg-stone-950/40 opacity-40'
                }`}
              >
                <div className={`font-mono text-[11px] tabular-nums ${isActive ? 'text-orange-200' : 'text-stone-500'}`}>
                  {opt.label}
                </div>
                <div className="text-[9px] uppercase tracking-wider text-stone-600 mt-0.5">{opt.sub}</div>
              </div>
            );
          })}
        </div>
      </div>

      {/* STAGE 3 — VOLUME (only if aggressive) */}
      {showVolume && (
        <div className="flex items-start gap-3">
          <span className="text-[9px] uppercase tracking-[0.2em] text-stone-600 font-mono w-16 shrink-0 pt-3">03 · Volume</span>
          <div className="flex-1 grid grid-cols-2 gap-2">
            {volumeOptions.map(opt => {
              const isActive = opt.id === volumeBucket;
              return (
                <div
                  key={opt.id}
                  className={`px-3 py-2.5 border transition-all ${
                    isActive
                      ? 'border-orange-500/60 bg-orange-500/10'
                      : 'border-stone-800/60 bg-stone-950/40 opacity-40'
                  }`}
                >
                  <div className={`font-mono text-[11px] tabular-nums ${isActive ? 'text-orange-200' : 'text-stone-500'}`}>
                    {opt.label}
                  </div>
                  <div className="text-[9px] uppercase tracking-wider text-stone-600 mt-0.5">{opt.sub}</div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* STAGE 4 — DECISION */}
      <div className="flex items-start gap-3">
        <span className="text-[9px] uppercase tracking-[0.2em] text-stone-600 font-mono w-16 shrink-0 pt-3">
          {showVolume ? '04' : '03'} · Action
        </span>
        <div className="flex-1 px-4 py-3 border border-orange-500/60 bg-gradient-to-r from-orange-500/15 to-orange-500/5 relative overflow-hidden">
          <div className="absolute inset-y-0 left-0 w-1 bg-orange-500" />
          <div className="font-anton text-2xl uppercase tracking-tight text-orange-200 mb-0.5">
            {analysis.decision.label}
          </div>
          <div className="text-[10px] uppercase tracking-wider text-stone-400 font-mono">
            {analysis.decision.kcalDelta > 0 ? '+' : ''}{analysis.decision.kcalDelta} kcal · {analysis.decision.deload ? 'deload week scheduled' : 'continue program'}
          </div>
        </div>
      </div>
    </div>
  );
}

// Macro recommendation card — old vs new with diff
function MacroDiff({ current, recommended }) {
  const rows = [
    { key: 'kcal',    label: 'Calories', unit: 'kcal',  cur: current.kcal,    rec: recommended.kcal,    big: true },
    { key: 'protein', label: 'Protein',  unit: 'g',     cur: current.protein, rec: recommended.protein },
    { key: 'carbs',   label: 'Carbs',    unit: 'g',     cur: current.carbs,   rec: recommended.carbs },
    { key: 'fat',     label: 'Fat',      unit: 'g',     cur: current.fat,     rec: recommended.fat },
  ];

  return (
    <div className="space-y-2">
      {rows.map(r => {
        const delta = r.rec - r.cur;
        const isPositive = delta > 0;
        const isZero = delta === 0;
        return (
          <div
            key={r.key}
            className={`grid grid-cols-12 items-baseline gap-2 px-4 ${r.big ? 'py-3' : 'py-2'} border ${
              isZero ? 'border-stone-800/60 bg-stone-950/40' : 'border-orange-500/30 bg-orange-500/5'
            }`}
          >
            <div className="col-span-3 text-[10px] uppercase tracking-wider text-stone-500 font-mono">
              {r.label}
            </div>
            <div className={`col-span-3 font-mono tabular-nums text-stone-500 line-through ${r.big ? 'text-base' : 'text-sm'}`}>
              {fmt0(r.cur)}{r.unit === 'g' && 'g'}
            </div>
            <div className="col-span-1 text-stone-700 font-mono text-xs">→</div>
            <div className={`col-span-3 font-anton tabular-nums ${r.big ? 'text-2xl' : 'text-lg'} ${isZero ? 'text-stone-300' : 'text-orange-300'}`}>
              {fmt0(r.rec)}{r.unit === 'g' && 'g'}
            </div>
            <div className={`col-span-2 text-right font-mono text-[11px] tabular-nums ${
              isZero ? 'text-stone-600' : isPositive ? 'text-orange-400' : 'text-red-400'
            }`}>
              {isZero ? '—' : `${isPositive ? '+' : ''}${delta}${r.unit === 'g' ? 'g' : ''}`}
            </div>
          </div>
        );
      })}
    </div>
  );
}

// Header stripe with phase + cycle countdown
function PhaseStripe({ ctx }) {
  return (
    <div className="flex items-center gap-4 text-xs font-mono">
      <span className="px-2 py-1 bg-orange-500/15 text-orange-300 border border-orange-500/30 uppercase tracking-wider">
        {ctx.goal}
      </span>
      <span className="text-stone-500">
        Week <span className="text-stone-300 tabular-nums">{ctx.programWeek}</span> / {ctx.programDuration}
      </span>
      <span className="text-stone-700">·</span>
      <span className="text-stone-500">
        Next analysis <span className="text-stone-300 tabular-nums">{ctx.daysUntilNext}d</span>
      </span>
    </div>
  );
}

// -------------------- MAIN --------------------
export default function CoachEngine() {
  const ctx = USER_CONTEXT;
  const [applied, setApplied] = useState(false);

  const analysis = useMemo(() => decideRecommendation(ctx), []);
  const recommended = useMemo(
    () => applyMacroDelta(ctx.currentMacros, analysis.decision.kcalDelta),
    [analysis.decision.kcalDelta]
  );
  const rationale = useMemo(() => generateRationale(ctx, analysis), [analysis]);

  const weightDelta = ctx.weightLog[0] - ctx.weightLog[ctx.weightLog.length - 1];
  const meanCalories = mean(ctx.calorieLog);
  const meanProtein = mean(ctx.proteinLog);
  const avgVolumeChange = mean(Object.values(ctx.volumeChange));
  const regressingCount = analysis.regressingMuscles.length;

  return (
    <div className="min-h-screen w-full bg-[#0a0908] text-stone-100 font-sans antialiased">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Anton&family=JetBrains+Mono:wght@400;500&family=Manrope:wght@400;500;600&display=swap');
        .font-sans  { font-family: 'Manrope', system-ui, sans-serif; }
        .font-mono  { font-family: 'JetBrains Mono', ui-monospace, monospace; }
        .font-anton { font-family: 'Anton', sans-serif; letter-spacing: 0.01em; }
        body { background: #0a0908; }
        @keyframes fadeUp { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: translateY(0); } }
        .reveal { animation: fadeUp 600ms ease-out both; }
      `}</style>

      <AppNav />

      {/* AMBIENT BACKDROP */}
      <div className="fixed inset-0 pointer-events-none" aria-hidden>
        <div className="absolute inset-0 opacity-[0.025]" style={{
          backgroundImage: 'repeating-linear-gradient(0deg, transparent 0, transparent 38px, #fff 38px, #fff 39px)'
        }} />
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[80vw] h-[40vh] opacity-[0.06] blur-3xl" style={{
          background: 'radial-gradient(ellipse, #ff5a2a 0%, transparent 60%)'
        }} />
      </div>

      <div className="relative z-10 max-w-[1280px] mx-auto px-6 py-8">

        {/* HEADER */}
        <header className="flex items-end justify-between gap-6 mb-8 pb-6 border-b border-stone-800/60">
          <div>
            <div className="flex items-baseline gap-3 mb-2">
              <span className="font-anton text-5xl uppercase tracking-tight text-stone-100">Oracle</span>
              <span className="font-anton text-5xl uppercase tracking-tight bg-gradient-to-br from-orange-300 to-orange-600 bg-clip-text text-transparent">Engine</span>
            </div>
            <PhaseStripe ctx={ctx} />
          </div>
          <div className="text-right">
            <div className="text-[9px] uppercase tracking-[0.2em] text-stone-600 font-mono mb-1">Analysis</div>
            <div className="font-mono text-xs text-stone-500">
              <span className="inline-block w-1.5 h-1.5 bg-orange-400 rounded-full mr-1.5 animate-pulse" />
              Generated {ctx.lastAnalyzed}
            </div>
            <div className="font-mono text-[10px] text-stone-700 mt-0.5">7-day rolling cycle · #4</div>
          </div>
        </header>

        {/* HEADLINE INSIGHT */}
        <div className="mb-10 reveal">
          <div className="text-[10px] uppercase tracking-[0.2em] text-stone-600 font-mono mb-2">Headline finding</div>
          <h1 className="font-anton text-5xl md:text-6xl uppercase tracking-tight leading-[0.95] text-stone-100 max-w-4xl">
            Cutting <span className="text-orange-400">{fmt(Math.abs(analysis.slopePctPerWeek), 2)}%</span> body weight per week
            — <span className="text-stone-500">faster than recovery allows.</span>
          </h1>
        </div>

        {/* INPUT STREAMS — three-card row showing the cross-module data */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-10">

          {/* Weight */}
          <div className="border border-stone-800/60 bg-stone-950/40 p-5 reveal" style={{ animationDelay: '60ms' }}>
            <div className="flex items-baseline justify-between mb-3">
              <span className="text-[10px] uppercase tracking-[0.18em] text-stone-500 font-mono">Body Comp</span>
              <span className="text-[9px] uppercase tracking-wider text-stone-700 font-mono">14d · vault</span>
            </div>
            <div className="font-anton text-4xl tabular-nums text-stone-100 mb-1">
              −{fmt(weightDelta, 1)}<span className="text-stone-500 text-2xl ml-1">kg</span>
            </div>
            <div className="text-[11px] font-mono text-orange-400 tabular-nums mb-4">
              slope {fmt(analysis.slopePctPerWeek, 2)}% bw / wk
            </div>
            <Sparkline values={ctx.weightLog} color="#ed7a2a" regression fill />
            <div className="flex justify-between text-[9px] font-mono text-stone-700 mt-1.5 tabular-nums">
              <span>{fmt(ctx.weightLog[0], 1)} kg</span>
              <span>{fmt(ctx.weightLog[ctx.weightLog.length-1], 1)} kg</span>
            </div>
          </div>

          {/* Nutrition */}
          <div className="border border-stone-800/60 bg-stone-950/40 p-5 reveal" style={{ animationDelay: '120ms' }}>
            <div className="flex items-baseline justify-between mb-3">
              <span className="text-[10px] uppercase tracking-[0.18em] text-stone-500 font-mono">Energy Intake</span>
              <span className="text-[9px] uppercase tracking-wider text-stone-700 font-mono">14d · nutrition</span>
            </div>
            <div className="font-anton text-4xl tabular-nums text-stone-100 mb-1">
              {fmt0(meanCalories)}<span className="text-stone-500 text-2xl ml-1">kcal</span>
            </div>
            <div className="text-[11px] font-mono text-stone-400 tabular-nums mb-4">
              {fmt0(meanProtein)}g protein · daily mean
            </div>
            <Sparkline values={ctx.calorieLog} color="#7eb6ff" fill />
            <div className="flex justify-between text-[9px] font-mono text-stone-700 mt-1.5 tabular-nums">
              <span>2,150 low</span>
              <span>2,240 high</span>
            </div>
          </div>

          {/* Training Stimulus */}
          <div className="border border-stone-800/60 bg-stone-950/40 p-5 reveal" style={{ animationDelay: '180ms' }}>
            <div className="flex items-baseline justify-between mb-3">
              <span className="text-[10px] uppercase tracking-[0.18em] text-stone-500 font-mono">Training Stim</span>
              <span className="text-[9px] uppercase tracking-wider text-stone-700 font-mono">14d · IRONLAB</span>
            </div>
            <div className="font-anton text-4xl tabular-nums text-stone-100 mb-1">
              {fmt(avgVolumeChange, 1)}<span className="text-stone-500 text-2xl ml-1">%</span>
            </div>
            <div className="text-[11px] font-mono tabular-nums mb-4">
              <span className="text-red-400">{regressingCount} regressing</span>
              <span className="text-stone-700"> · </span>
              <span className="text-stone-500">{Object.keys(ctx.volumeChange).length - regressingCount} stable</span>
            </div>
            <VolumeChangeChart data={ctx.volumeChange} />
          </div>
        </div>

        {/* DECISION GATE + RECOMMENDATION — two-column */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 mb-10">

          {/* DECISION FLOW */}
          <div className="lg:col-span-7 border border-stone-800/60 bg-stone-950/40 p-6 reveal" style={{ animationDelay: '240ms' }}>
            <div className="flex items-baseline justify-between mb-5">
              <h2 className="font-anton text-2xl uppercase tracking-tight text-stone-100">Decision Gate</h2>
              <span className="text-[9px] uppercase tracking-[0.18em] text-stone-600 font-mono">deterministic · rule-based</span>
            </div>
            <DecisionFlow analysis={analysis} />
            <div className="mt-5 pt-4 border-t border-stone-800/60 text-[10px] font-mono text-stone-600 leading-relaxed">
              Rules execute server-side as a pure function. Same inputs ⇒ same output, every time.
              The narrative below is generated by Claude given identical context — explanation, not decision.
            </div>
          </div>

          {/* MACRO DIFF */}
          <div className="lg:col-span-5 border border-stone-800/60 bg-stone-950/40 p-6 reveal" style={{ animationDelay: '300ms' }}>
            <div className="flex items-baseline justify-between mb-5">
              <h2 className="font-anton text-2xl uppercase tracking-tight text-stone-100">New Macros</h2>
              <span className="text-[9px] uppercase tracking-[0.18em] text-stone-600 font-mono">apply for 7 days</span>
            </div>
            <MacroDiff current={ctx.currentMacros} recommended={recommended} />
            <div className="mt-4 grid grid-cols-3 gap-2 text-center">
              {[
                { l: 'P', v: Math.round((recommended.protein * 4 / recommended.kcal) * 100), c: 'text-orange-300' },
                { l: 'C', v: Math.round((recommended.carbs * 4 / recommended.kcal) * 100), c: 'text-stone-300' },
                { l: 'F', v: Math.round((recommended.fat * 9 / recommended.kcal) * 100), c: 'text-stone-300' },
              ].map(x => (
                <div key={x.l} className="border border-stone-800/60 py-2 bg-stone-950/40">
                  <div className="text-[9px] font-mono uppercase text-stone-600 tracking-wider">{x.l}</div>
                  <div className={`font-anton text-lg tabular-nums ${x.c}`}>{x.v}%</div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* RATIONALE */}
        <div className="border border-stone-800/60 bg-gradient-to-b from-stone-950/40 to-stone-950/80 p-6 mb-8 reveal" style={{ animationDelay: '360ms' }}>
          <div className="flex items-baseline justify-between mb-3">
            <h2 className="font-anton text-2xl uppercase tracking-tight text-stone-100">Oracle Rationale</h2>
            <span className="text-[9px] uppercase tracking-[0.18em] text-stone-600 font-mono">claude · narrative layer</span>
          </div>
          <p className="text-stone-300 leading-relaxed text-[15px] max-w-3xl">
            {rationale}
          </p>
        </div>

        {/* ACTIONS */}
        <div className="flex flex-wrap items-center justify-between gap-4 reveal" style={{ animationDelay: '420ms' }}>
          <div className="text-[10px] font-mono uppercase tracking-wider text-stone-600">
            Reviewed by <span className="text-stone-400">{ctx.name}</span> · auto-applied if no action in 24h
          </div>
          <div className="flex gap-2">
            <button className="px-5 py-2.5 border border-stone-700 text-stone-400 font-anton text-sm uppercase tracking-wider hover:bg-stone-800 hover:text-stone-200 transition-colors">
              Adjust manually
            </button>
            <button
              onClick={() => setApplied(true)}
              disabled={applied}
              className={`px-6 py-2.5 font-anton text-sm uppercase tracking-wider transition-all ${
                applied
                  ? 'bg-stone-800 text-stone-500 cursor-not-allowed'
                  : 'bg-orange-500 text-stone-950 hover:bg-orange-400'
              }`}
            >
              {applied ? '✓ Applied · synced to nutrition' : 'Apply for next 7 days →'}
            </button>
          </div>
        </div>

        {/* FOOTER */}
        <footer className="mt-12 pt-6 border-t border-stone-800/60 flex items-center justify-between text-[10px] uppercase tracking-wider text-stone-600 font-mono">
          <span>Oracle v0.4 · Module 5 · Cross-module synthesis</span>
          <span>Inputs: vault · nutrition · IRONLAB · 14d window</span>
        </footer>
      </div>
    </div>
  );
}
